function cql_filter_geom = create_geom_cql(lon_lat_left_bottom,lon_lat_right_top)
% create_geom_cql create the geometry CQL filter part from a bounding box coordinates

lon_lat_corner1 = [lon_lat_left_bottom(1), lon_lat_left_bottom(2)];
lon_lat_corner2 = [lon_lat_left_bottom(1),lon_lat_right_top(2)];
lon_lat_corner3 = [lon_lat_right_top(1), lon_lat_right_top(2)];
lon_lat_corner4 = [lon_lat_right_top(1), lon_lat_left_bottom(2)];

geomType        = 'POLYGON';
cql_filter_geom = [ 'INTERSECTS(geom,' geomType '((' ...
                    num2str(lon_lat_corner1(1)) ' ' num2str(lon_lat_corner1(2)) ','...
                    num2str(lon_lat_corner2(1)) ' ' num2str(lon_lat_corner2(2)) ','...
                    num2str(lon_lat_corner3(1)) ' ' num2str(lon_lat_corner3(2)) ','...
                    num2str(lon_lat_corner4(1)) ' ' num2str(lon_lat_corner4(2)) ','...
                    num2str(lon_lat_corner1(1)) ' ' num2str(lon_lat_corner1(2)) ...
                    ')))'];
