site :opscode

cookbook "apt"
cookbook "python"
cookbook "imos_python", :github => "aodn/cookbooks", :rel => "imos_python"
cookbook "r", :github => "stevendanna/cookbook-r"
cookbook "imos_r", :github => "aodn/cookbooks", :rel => "imos_r"
cookbook "git"
cookbook "imos_user_code_library", :github => "aodn/cookbooks", :rel => "imos_user_code_library"
